Docker
filip-michalsky/SalesGPT pull request #119
Opened 2024-03-14 11:13 UTC by chemik-bit

Added docker functionality.

2024-03-19 21:38 UTC, filip-michalsky commented on Dockerfile.backend
@iljamak unfortunately, Docker does not play nicely with poetry, right @chemik-bit ? So i would probably keep as is for the docker deployment.

2024-03-20 17:02 UTC, filip-michalsky commented on frontend/Dockerfile.frontend
@iljamak I think this is fine for now - don't see an issue with it? Please add as an issue into "Issues" for a future consideration

2024-03-20 18:12 UTC, filip-michalsky requested changes
great job! requested a few changes including keeping some instructions which were deleted.

2024-03-20 18:12 UTC, filip-michalsky commented on README.md
> +   `docker-compose up`
`docker compose up -d --build` ?

if errors, run:
`docker system prune --volumes`
`docker compose up -d --build --no-cache` ?

2024-03-20 18:12 UTC, filip-michalsky commented on README.md
> +This will build and start the necessary Docker containers for SalesGPT. You can then access the application by opening the following link in any of your browsers: [localhost:3000/chat](http://localho
let's route the root to redirect to /chat

2024-03-22 14:55 UTC, chemik-bit commented on Dockerfile.backend
Docker does not currently work with poetry too well, so pip is commonly used. If poetry support is extended will transfer right away!

2024-03-22 14:57 UTC, chemik-bit commented on frontend/Dockerfile.frontend
I added this as a new issue. Will address in the future, will increase priority if upvoted by users.

2024-03-22 17:13 UTC, filip-michalsky commented
@chemik-bit great job!

2024-03-22 17:14 UTC, filip-michalsky approved these changes

2024-03-22 17:14 UTC, merged