Add support for Llama2, Palm, Cohere, Anthropic, Replicate, Azure Models - using litellm
filip-michalsky/SalesGPT pull request #36
Opened 2023-08-18 23:54 UTC by ishaan-jaff

This PR adds support for 50+ models with a standard I/O interface using: https://github.com/BerriAI/litellm/

`ChatLiteLLM()` is integrated into langchain and allows you to call all models using the ChatOpenAI I/O interface 
https://python.langchain.com/docs/integrations/chat/litellm

Here's an example of how to use ChatLiteLLM()
```python
ChatLiteLLM(model="gpt-3.5-turbo")
ChatLiteLLM(model="claude-2", temperature=0.3)
ChatLiteLLM(model="command-nightly")
ChatLiteLLM(model="replicate/llama-2-70b-chat:2c1608e18606fad2812020dc541930f2d0495ce32eee50074220b87300bc16e1")

```

2023-08-18 23:55 UTC, ishaan-jaff commented
@filip-michalsky can I get a review on this PR please😊

if this initial commit looks good happy to add more docs/ tests too

2023-08-21 03:24 UTC, sunyilong0 commented
so good

2023-08-21 20:21 UTC, krrishdholakia commented
bump on this? @filip-michalsky

2023-08-23 17:48 UTC, filip-michalsky commented
Need to add docs:

pip installs necessary 
- google-generativeai (version?)
- `langchain` minimum version where `litellm` was merged?

2023-08-23 17:49 UTC, filip-michalsky commented
Just checkout out the PR locally and running to this error:

  File "/Users/filipmichalsky/Odyssey/sales_bot/SalesGPT/run.py", line 34, in <module>
    llm = ChatLiteLLM(temperature=0.2)
  File "/Users/filipmichalsky/anaconda3/envs/salesgpt/lib/python3.10/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1102, in pydantic.main.validate_model
  File "/Users/filipmichalsky/anaconda3/envs/salesgpt/lib/python3.10/site-packages/langchain/chat_models/litellm.py", line 285, in validate_environment
    raise ChatLiteLLMException(
langchain.chat_models.litellm.ChatLiteLLMException: Could not import google.generativeai python package. Please install it with `pip install google-generativeai`

2023-08-23 17:58 UTC, filip-michalsky requested changes
Thanks so much for your PR!

I reviewed and I am OK with using ChatLiteLLM inside SalesGPT to give users easy access to different backend LLMs.

We need a few quality improvements:

Need to add reproducibility instructions:

- Minimum library versions to `requirements.txt`

I am not convinced this will work for the streaming generator function per my comment unless you are mimicking core `langchain` `completion_with_retry` signature.

I was unable to run `python run.py` example with this library.

Please update tests as well.

2023-08-23 17:58 UTC, filip-michalsky commented on examples/streaming_generator_example.py
> +llm = ChatLiteLLM(temperature=0.9)
Does this library support `https://github.com/filip-michalsky/SalesGPT/blob/main/salesgpt/agents.py#L139`?

we are leveraging `completion_with_retry` from core langchain.

2023-09-02 22:39 UTC, ishaan-jaff commented
@filip-michalsky i tried our langchain integration on a notebook and it worked fine - there was no dependency for 

notebook: https://colab.research.google.com/drive/1IqBFz5YXIoa8XahPb3qslmg3UoWVMUR_#scrollTo=TahkCtlmCD65

2023-09-02 22:41 UTC, ishaan-jaff commented
here's what's remaining for this PR:
@filip-michalsky  lmk if anything is missing

- verify streaming works 
- update requirements.txt 
- Add troubleshooting to readme incase users see google-generativeai error 
- verify completion_with_retry works with ChatLiteLLM

2023-09-02 22:48 UTC, ishaan-jaff commented
as for updating requirements.txt, i'm not sure we should add `google-cloud-aiplatform` as a dependency to this project. We should only add instructions to `pip install google-cloud-aiplatform` if users are trying VertexAI LLMs

2023-09-02 23:00 UTC, ishaan-jaff commented
<img width="1280" alt="Screenshot 2023-09-02 at 3 57 28 PM" src="https://github.com/filip-michalsky/SalesGPT/assets/29436595/0215af60-eb21-4058-9d36-7c88d7114e09">

I can confirm the current fixes work locally when running run.py

2023-09-02 23:07 UTC, ishaan-jaff commented
Can confirm it works with your streaming generator too:
<img width="1226" alt="Screenshot 2023-09-02 at 4 06 53 PM" src="https://github.com/filip-michalsky/SalesGPT/assets/29436595/f5a257b1-3336-4857-8175-88481196218d">

2023-09-02 23:10 UTC, ishaan-jaff commented
Can confirm we support completion_with_retry:
https://github.com/langchain-ai/langchain/blob/0e4c5dd1767b53e212d63bc81cceb7270178c322/libs/langchain/langchain/chat_models/litellm.py#L267

2023-09-03 16:58 UTC, filip-michalsky commented
> @filip-michalsky i tried our langchain integration on a notebook and it worked fine - there was no dependency for google-generativeai
> 
> notebook: https://colab.research.google.com/drive/1IqBFz5YXIoa8XahPb3qslmg3UoWVMUR_#scrollTo=TahkCtlmCD65

Pls give me access so I can see the notebook :-)

2023-09-03 17:13 UTC, filip-michalsky commented
> as for updating requirements.txt, i'm not sure we should add `google-cloud-aiplatform` as a dependency to this project. We should only add instructions to `pip install google-cloud-aiplatform` if users are trying VertexAI LLMs

Please add to `requirements.txt`
litellm>=

I have verified this version runs both in `run.py` and the streaming example. I also don't run into the GCP api dependency issue and agreed it should not be included in the SalesGPT project.

2023-09-03 17:17 UTC, filip-michalsky commented
> here's what's remaining for this PR: @filip-michalsky lmk if anything is missing
> 
> * verify it works when running run.py (Done)
> * verify streaming works (Done)
> * update requirements.txt (waiting for @filip-michalsky for feedback on this)
> * Add troubleshooting to readme incase users see google-generativeai error (waiting for @filip-michalsky for feedback on this)
> * verify completion_with_retry works with ChatLiteLLM (Done)

Thank you!

It seems that you don't support asynchronous execution yet? 

I updated [this line](https://github.com/filip-michalsky/SalesGPT/pull/36/files#diff-cadc3583be4ac99d77c9eb47ad3352a1389db9caa55a5728e9a9e0e8a5a2aac0R121) in `test_salesgpt.py` with ChatLiteLLM and got the following error:


FAILED tests/test_salesgpt.py::TestSalesGPT::test_valid_async_inference_stream - AttributeError: module 'litellm' has no attribute 'acreate'

2023-09-03 17:19 UTC, filip-michalsky commented
@ishaan-jaff thanks a lot for the PR update. Looks good from all the above, just need to add support for `acompletion_with_retry` to be fully compatible with current SalesGPT agent.

What is your ETA on supporting this if it's on the roadmap?

https://github.com/langchain-ai/langchain/blob/0e4c5dd1767b53e212d63bc81cceb7270178c322/libs/langchain/langchain/chat_models/openai.py#L79

Thank you!!

2023-09-04 18:09 UTC, krrishdholakia commented
Hey @filip-michalsky will work on getting this done today

2023-09-05 12:28 UTC, filip-michalsky commented
@krrishdholakia sounds good!

2023-09-05 17:57 UTC, luolin-ai commented
> This PR adds support for 50+ models with a standard I/O interface using: https://github.com/BerriAI/litellm/
> 
> `ChatLiteLLM()` is integrated into langchain and allows you to call all models using the `ChatOpenAI` I/O interface https://python.langchain.com/docs/integrations/chat/litellm
> 
> Here's an example of how to use ChatLiteLLM()
> 
> ```python
> ChatLiteLLM(model="gpt-3.5-turbo")
> ChatLiteLLM(model="claude-2", temperature=0.3)
> ChatLiteLLM(model="command-nightly")
> ChatLiteLLM(model="replicate/llama-2-70b-chat:2c1608e18606fad2812020dc541930f2d0495ce32eee50074220b87300bc16e1")
> ```

以实现

2023-09-05 21:01 UTC, filip-michalsky commented
@ishaan-jaff @krrishdholakia looks like async streaming is supported now - @ishaan-jaff I am happy to push to your fork to update the async generator. Also I find it super neat you can a/b test models. For me, I would love to a/b test all the LLMs supported on a given use case and benchmark for latency

2023-09-05 21:05 UTC, krrishdholakia commented
Do you mean a/b test on a local script / jupyter notebook or in production? 

For local testing - https://docs.litellm.ai/docs/tutorials/compare_llms
For production - https://docs.litellm.ai/docs/tutorials/ab_test_llms

2023-09-05 21:07 UTC, filip-michalsky commented
@krrishdholakia locally or in staging

2023-09-05 21:10 UTC, krrishdholakia commented
Oh - why run this in staging?

2023-09-05 21:14 UTC, filip-michalsky commented
@krrishdholakia network latency replication -duplicate prod. This is getting off-topic from the PR, happy to chat separately. @ishaan-jaff  lmk on the async streaming generator, happy to push to your fork (not sure of the workflow of pushing to someone else's fork of a repo though, have not done this before)

2023-09-06 03:31 UTC, ishaan-jaff commented
@filip-michalsky updated requirements.txt to add litellm 

Pending tasks:
- looks like ChatLiteLLM failed for `acompletion_with_retry`. @filip-michalsky do you want to address that in this PR too? 
(since this PR does not edit https://github.com/langchain-ai/langchain/blob/0e4c5dd1767b53e212d63bc81cceb7270178c322/libs/langchain/langchain/chat_models/openai.py#L79)

If it makes sense happy to address that in the next PR

2023-09-06 21:21 UTC, filip-michalsky commented
@ishaan-jaff 

SalesGPT actually has it's own `acompletion_with_retry` which can be updated inpdependent of `langchain`
https://github.com/filip-michalsky/SalesGPT/blob/main/salesgpt/agents.py#L185

I just tried this:

```
from litellm import acompletion

    async def acompletion_with_retry(self, llm: Any, **kwargs: Any) -> Any:
        """Use tenacity to retry the async completion call."""
        retry_decorator = _create_retry_decorator(llm)

        @retry_decorator
        async def _completion_with_retry(**kwargs: Any) -> Any:
            # Use OpenAI's async api https://github.com/openai/openai-python#async-api
            return await acompletion(**kwargs)

        return await _completion_with_retry(**kwargs)
```
This does not pass the async test since the object returned from litellm acompletion method with stream=True is *not* an async generator.

I feel we need to address this in this PR and hopefully will improve your `litellm` codebase as well. (When combining streaming with async, I would expect the returning object is an asynchronous generator).

Thank you!

2023-09-07 04:52 UTC, ishaan-jaff commented
@filip-michalsky sounds good - tracking this here: https://github.com/BerriAI/litellm/issues/292 

will aim to have this done in the next 12 hours 

Agree- we should fix this in this PR and it will def make LiteLLM better too

2023-09-07 21:20 UTC, ishaan-jaff commented
confirming tests pass on latest litellm version + with using litellm.acompletion 

<img width="1280" alt="Screenshot 2023-09-07 at 2 18 25 PM" src="https://github.com/filip-michalsky/SalesGPT/assets/29436595/248c3654-6377-471d-94a2-dd93dc7d55e8">

2023-09-07 21:21 UTC, ishaan-jaff commented on requirements.txt
> +langchain>=0.0.281
0.0.281 has the latest LiteLLM updates to langchain: 
https://github.com/langchain-ai/langchain/releases

2023-09-07 21:21 UTC, ishaan-jaff commented on requirements.txt
> +litellm>=0.1.558
version with support for returning async generators

2023-09-07 21:22 UTC, ishaan-jaff commented
done @filip-michalsky 

lmk if any other changes needed

2023-09-08 17:45 UTC, filip-michalsky commented
@ishaan-jaff amazing! I see you did not update the test, but when I did, it passes now. I will just send a quick new PR to update test/changelog etc but you are good to go :) would love to have SalesGPT as one of the projects using LiteLLM on your docs :)

Thanks,

Filip

2023-09-08 17:45 UTC, merged